/* 
 * E-commerce API
 *
 * API for E-commerce Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandon.dunbar97@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Affiliate
    /// </summary>
    [DataContract]
        public partial class Affiliate :  IEquatable<Affiliate>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Affiliate" /> class.
        /// </summary>
        /// <param name="affiliateId">Unique identifier for the affiliate. (required).</param>
        /// <param name="name">Full name or company name of the affiliate. (required).</param>
        /// <param name="contactEmail">Contact email address for the affiliate. (required).</param>
        /// <param name="referralCode">Unique code used by the affiliate for referrals. (required).</param>
        /// <param name="registrationDate">Date and time when the affiliate was onboarded. (required).</param>
        /// <param name="totalReferrals">Total number of referrals made by the affiliate..</param>
        /// <param name="successfulReferrals">Number of successful referrals that resulted in sales or signups..</param>
        /// <param name="commissionEarned">Total commission earned by the affiliate based on successful referrals..</param>
        /// <param name="isActive">Indicates whether the affiliate is currently active..</param>
        public Affiliate(long? affiliateId = default(long?), string name = default(string), string contactEmail = default(string), string referralCode = default(string), DateTime? registrationDate = default(DateTime?), int? totalReferrals = default(int?), int? successfulReferrals = default(int?), float? commissionEarned = default(float?), bool? isActive = default(bool?))
        {
            // to ensure "affiliateId" is required (not null)
            if (affiliateId == null)
            {
                throw new InvalidDataException("affiliateId is a required property for Affiliate and cannot be null");
            }
            else
            {
                this.AffiliateId = affiliateId;
            }
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for Affiliate and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            // to ensure "contactEmail" is required (not null)
            if (contactEmail == null)
            {
                throw new InvalidDataException("contactEmail is a required property for Affiliate and cannot be null");
            }
            else
            {
                this.ContactEmail = contactEmail;
            }
            // to ensure "referralCode" is required (not null)
            if (referralCode == null)
            {
                throw new InvalidDataException("referralCode is a required property for Affiliate and cannot be null");
            }
            else
            {
                this.ReferralCode = referralCode;
            }
            // to ensure "registrationDate" is required (not null)
            if (registrationDate == null)
            {
                throw new InvalidDataException("registrationDate is a required property for Affiliate and cannot be null");
            }
            else
            {
                this.RegistrationDate = registrationDate;
            }
            this.TotalReferrals = totalReferrals;
            this.SuccessfulReferrals = successfulReferrals;
            this.CommissionEarned = commissionEarned;
            this.IsActive = isActive;
        }
        
        /// <summary>
        /// Unique identifier for the affiliate.
        /// </summary>
        /// <value>Unique identifier for the affiliate.</value>
        [DataMember(Name="affiliateId", EmitDefaultValue=false)]
        public long? AffiliateId { get; set; }

        /// <summary>
        /// Full name or company name of the affiliate.
        /// </summary>
        /// <value>Full name or company name of the affiliate.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Contact email address for the affiliate.
        /// </summary>
        /// <value>Contact email address for the affiliate.</value>
        [DataMember(Name="contactEmail", EmitDefaultValue=false)]
        public string ContactEmail { get; set; }

        /// <summary>
        /// Unique code used by the affiliate for referrals.
        /// </summary>
        /// <value>Unique code used by the affiliate for referrals.</value>
        [DataMember(Name="referralCode", EmitDefaultValue=false)]
        public string ReferralCode { get; set; }

        /// <summary>
        /// Date and time when the affiliate was onboarded.
        /// </summary>
        /// <value>Date and time when the affiliate was onboarded.</value>
        [DataMember(Name="registrationDate", EmitDefaultValue=false)]
        public DateTime? RegistrationDate { get; set; }

        /// <summary>
        /// Total number of referrals made by the affiliate.
        /// </summary>
        /// <value>Total number of referrals made by the affiliate.</value>
        [DataMember(Name="totalReferrals", EmitDefaultValue=false)]
        public int? TotalReferrals { get; set; }

        /// <summary>
        /// Number of successful referrals that resulted in sales or signups.
        /// </summary>
        /// <value>Number of successful referrals that resulted in sales or signups.</value>
        [DataMember(Name="successfulReferrals", EmitDefaultValue=false)]
        public int? SuccessfulReferrals { get; set; }

        /// <summary>
        /// Total commission earned by the affiliate based on successful referrals.
        /// </summary>
        /// <value>Total commission earned by the affiliate based on successful referrals.</value>
        [DataMember(Name="commissionEarned", EmitDefaultValue=false)]
        public float? CommissionEarned { get; set; }

        /// <summary>
        /// Indicates whether the affiliate is currently active.
        /// </summary>
        /// <value>Indicates whether the affiliate is currently active.</value>
        [DataMember(Name="isActive", EmitDefaultValue=false)]
        public bool? IsActive { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Affiliate {\n");
            sb.Append("  AffiliateId: ").Append(AffiliateId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ContactEmail: ").Append(ContactEmail).Append("\n");
            sb.Append("  ReferralCode: ").Append(ReferralCode).Append("\n");
            sb.Append("  RegistrationDate: ").Append(RegistrationDate).Append("\n");
            sb.Append("  TotalReferrals: ").Append(TotalReferrals).Append("\n");
            sb.Append("  SuccessfulReferrals: ").Append(SuccessfulReferrals).Append("\n");
            sb.Append("  CommissionEarned: ").Append(CommissionEarned).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Affiliate);
        }

        /// <summary>
        /// Returns true if Affiliate instances are equal
        /// </summary>
        /// <param name="input">Instance of Affiliate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Affiliate input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AffiliateId == input.AffiliateId ||
                    (this.AffiliateId != null &&
                    this.AffiliateId.Equals(input.AffiliateId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.ContactEmail == input.ContactEmail ||
                    (this.ContactEmail != null &&
                    this.ContactEmail.Equals(input.ContactEmail))
                ) && 
                (
                    this.ReferralCode == input.ReferralCode ||
                    (this.ReferralCode != null &&
                    this.ReferralCode.Equals(input.ReferralCode))
                ) && 
                (
                    this.RegistrationDate == input.RegistrationDate ||
                    (this.RegistrationDate != null &&
                    this.RegistrationDate.Equals(input.RegistrationDate))
                ) && 
                (
                    this.TotalReferrals == input.TotalReferrals ||
                    (this.TotalReferrals != null &&
                    this.TotalReferrals.Equals(input.TotalReferrals))
                ) && 
                (
                    this.SuccessfulReferrals == input.SuccessfulReferrals ||
                    (this.SuccessfulReferrals != null &&
                    this.SuccessfulReferrals.Equals(input.SuccessfulReferrals))
                ) && 
                (
                    this.CommissionEarned == input.CommissionEarned ||
                    (this.CommissionEarned != null &&
                    this.CommissionEarned.Equals(input.CommissionEarned))
                ) && 
                (
                    this.IsActive == input.IsActive ||
                    (this.IsActive != null &&
                    this.IsActive.Equals(input.IsActive))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AffiliateId != null)
                    hashCode = hashCode * 59 + this.AffiliateId.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.ContactEmail != null)
                    hashCode = hashCode * 59 + this.ContactEmail.GetHashCode();
                if (this.ReferralCode != null)
                    hashCode = hashCode * 59 + this.ReferralCode.GetHashCode();
                if (this.RegistrationDate != null)
                    hashCode = hashCode * 59 + this.RegistrationDate.GetHashCode();
                if (this.TotalReferrals != null)
                    hashCode = hashCode * 59 + this.TotalReferrals.GetHashCode();
                if (this.SuccessfulReferrals != null)
                    hashCode = hashCode * 59 + this.SuccessfulReferrals.GetHashCode();
                if (this.CommissionEarned != null)
                    hashCode = hashCode * 59 + this.CommissionEarned.GetHashCode();
                if (this.IsActive != null)
                    hashCode = hashCode * 59 + this.IsActive.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
