/* 
 * E-commerce API
 *
 * API for E-commerce Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandon.dunbar97@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// ProductInventoryUpdate
    /// </summary>
    [DataContract]
        public partial class ProductInventoryUpdate :  IEquatable<ProductInventoryUpdate>, IValidatableObject
    {
        /// <summary>
        /// Updated inventory status.
        /// </summary>
        /// <value>Updated inventory status.</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum StatusEnum
        {
            /// <summary>
            /// Enum Instock for value: in_stock
            /// </summary>
            [EnumMember(Value = "in_stock")]
            Instock = 1,
            /// <summary>
            /// Enum Lowstock for value: low_stock
            /// </summary>
            [EnumMember(Value = "low_stock")]
            Lowstock = 2,
            /// <summary>
            /// Enum Outofstock for value: out_of_stock
            /// </summary>
            [EnumMember(Value = "out_of_stock")]
            Outofstock = 3        }
        /// <summary>
        /// Updated inventory status.
        /// </summary>
        /// <value>Updated inventory status.</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductInventoryUpdate" /> class.
        /// </summary>
        /// <param name="stockLevel">Updated number of items in stock..</param>
        /// <param name="status">Updated inventory status..</param>
        public ProductInventoryUpdate(int? stockLevel = default(int?), StatusEnum? status = default(StatusEnum?))
        {
            this.StockLevel = stockLevel;
            this.Status = status;
        }
        
        /// <summary>
        /// Updated number of items in stock.
        /// </summary>
        /// <value>Updated number of items in stock.</value>
        [DataMember(Name="stockLevel", EmitDefaultValue=false)]
        public int? StockLevel { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductInventoryUpdate {\n");
            sb.Append("  StockLevel: ").Append(StockLevel).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProductInventoryUpdate);
        }

        /// <summary>
        /// Returns true if ProductInventoryUpdate instances are equal
        /// </summary>
        /// <param name="input">Instance of ProductInventoryUpdate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductInventoryUpdate input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.StockLevel == input.StockLevel ||
                    (this.StockLevel != null &&
                    this.StockLevel.Equals(input.StockLevel))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.StockLevel != null)
                    hashCode = hashCode * 59 + this.StockLevel.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
