/* 
 * E-commerce API
 *
 * API for E-commerce Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandon.dunbar97@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// PromotionUpdate
    /// </summary>
    [DataContract]
        public partial class PromotionUpdate :  IEquatable<PromotionUpdate>, IValidatableObject
    {
        /// <summary>
        /// Type of promotion, e.g., percentage discount, flat discount, etc.
        /// </summary>
        /// <value>Type of promotion, e.g., percentage discount, flat discount, etc.</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum TypeEnum
        {
            /// <summary>
            /// Enum Percentage for value: percentage
            /// </summary>
            [EnumMember(Value = "percentage")]
            Percentage = 1,
            /// <summary>
            /// Enum Flatdiscount for value: flat_discount
            /// </summary>
            [EnumMember(Value = "flat_discount")]
            Flatdiscount = 2,
            /// <summary>
            /// Enum Buyonegetone for value: buy_one_get_one
            /// </summary>
            [EnumMember(Value = "buy_one_get_one")]
            Buyonegetone = 3,
            /// <summary>
            /// Enum Other for value: other
            /// </summary>
            [EnumMember(Value = "other")]
            Other = 4        }
        /// <summary>
        /// Type of promotion, e.g., percentage discount, flat discount, etc.
        /// </summary>
        /// <value>Type of promotion, e.g., percentage discount, flat discount, etc.</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PromotionUpdate" /> class.
        /// </summary>
        /// <param name="promotionId">Unique identifier for the promotion. This is typically used for reference and not for update purposes..</param>
        /// <param name="name">Updated name or title of the promotion..</param>
        /// <param name="type">Type of promotion, e.g., percentage discount, flat discount, etc..</param>
        /// <param name="value">The value associated with the promotion. For example, if it&#x27;s a percentage discount, this might be \&quot;10\&quot; for 10%..</param>
        /// <param name="startDate">Updated start date and time for when the promotion becomes active..</param>
        /// <param name="endDate">Updated end date and time for when the promotion expires..</param>
        /// <param name="applicableProducts">List of product IDs to which the promotion is applicable. If empty, it might be applicable to all products or specific categories..</param>
        /// <param name="notes">Any additional notes or updates about the promotion..</param>
        public PromotionUpdate(long? promotionId = default(long?), string name = default(string), TypeEnum? type = default(TypeEnum?), decimal? value = default(decimal?), DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), List<long?> applicableProducts = default(List<long?>), string notes = default(string))
        {
            this.PromotionId = promotionId;
            this.Name = name;
            this.Type = type;
            this.Value = value;
            this.StartDate = startDate;
            this.EndDate = endDate;
            this.ApplicableProducts = applicableProducts;
            this.Notes = notes;
        }
        
        /// <summary>
        /// Unique identifier for the promotion. This is typically used for reference and not for update purposes.
        /// </summary>
        /// <value>Unique identifier for the promotion. This is typically used for reference and not for update purposes.</value>
        [DataMember(Name="promotionId", EmitDefaultValue=false)]
        public long? PromotionId { get; set; }

        /// <summary>
        /// Updated name or title of the promotion.
        /// </summary>
        /// <value>Updated name or title of the promotion.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }


        /// <summary>
        /// The value associated with the promotion. For example, if it&#x27;s a percentage discount, this might be \&quot;10\&quot; for 10%.
        /// </summary>
        /// <value>The value associated with the promotion. For example, if it&#x27;s a percentage discount, this might be \&quot;10\&quot; for 10%.</value>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public decimal? Value { get; set; }

        /// <summary>
        /// Updated start date and time for when the promotion becomes active.
        /// </summary>
        /// <value>Updated start date and time for when the promotion becomes active.</value>
        [DataMember(Name="startDate", EmitDefaultValue=false)]
        public DateTime? StartDate { get; set; }

        /// <summary>
        /// Updated end date and time for when the promotion expires.
        /// </summary>
        /// <value>Updated end date and time for when the promotion expires.</value>
        [DataMember(Name="endDate", EmitDefaultValue=false)]
        public DateTime? EndDate { get; set; }

        /// <summary>
        /// List of product IDs to which the promotion is applicable. If empty, it might be applicable to all products or specific categories.
        /// </summary>
        /// <value>List of product IDs to which the promotion is applicable. If empty, it might be applicable to all products or specific categories.</value>
        [DataMember(Name="applicableProducts", EmitDefaultValue=false)]
        public List<long?> ApplicableProducts { get; set; }

        /// <summary>
        /// Any additional notes or updates about the promotion.
        /// </summary>
        /// <value>Any additional notes or updates about the promotion.</value>
        [DataMember(Name="notes", EmitDefaultValue=false)]
        public string Notes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PromotionUpdate {\n");
            sb.Append("  PromotionId: ").Append(PromotionId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  StartDate: ").Append(StartDate).Append("\n");
            sb.Append("  EndDate: ").Append(EndDate).Append("\n");
            sb.Append("  ApplicableProducts: ").Append(ApplicableProducts).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PromotionUpdate);
        }

        /// <summary>
        /// Returns true if PromotionUpdate instances are equal
        /// </summary>
        /// <param name="input">Instance of PromotionUpdate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PromotionUpdate input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PromotionId == input.PromotionId ||
                    (this.PromotionId != null &&
                    this.PromotionId.Equals(input.PromotionId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                ) && 
                (
                    this.StartDate == input.StartDate ||
                    (this.StartDate != null &&
                    this.StartDate.Equals(input.StartDate))
                ) && 
                (
                    this.EndDate == input.EndDate ||
                    (this.EndDate != null &&
                    this.EndDate.Equals(input.EndDate))
                ) && 
                (
                    this.ApplicableProducts == input.ApplicableProducts ||
                    this.ApplicableProducts != null &&
                    input.ApplicableProducts != null &&
                    this.ApplicableProducts.SequenceEqual(input.ApplicableProducts)
                ) && 
                (
                    this.Notes == input.Notes ||
                    (this.Notes != null &&
                    this.Notes.Equals(input.Notes))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PromotionId != null)
                    hashCode = hashCode * 59 + this.PromotionId.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                if (this.StartDate != null)
                    hashCode = hashCode * 59 + this.StartDate.GetHashCode();
                if (this.EndDate != null)
                    hashCode = hashCode * 59 + this.EndDate.GetHashCode();
                if (this.ApplicableProducts != null)
                    hashCode = hashCode * 59 + this.ApplicableProducts.GetHashCode();
                if (this.Notes != null)
                    hashCode = hashCode * 59 + this.Notes.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
