/* 
 * E-commerce API
 *
 * API for E-commerce Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandon.dunbar97@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// UserActivityReportTopVisitedPages
    /// </summary>
    [DataContract]
        public partial class UserActivityReportTopVisitedPages :  IEquatable<UserActivityReportTopVisitedPages>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserActivityReportTopVisitedPages" /> class.
        /// </summary>
        /// <param name="pageName">Name or identifier of the page..</param>
        /// <param name="visitCount">Number of visits to this page during the report period..</param>
        public UserActivityReportTopVisitedPages(string pageName = default(string), int? visitCount = default(int?))
        {
            this.PageName = pageName;
            this.VisitCount = visitCount;
        }
        
        /// <summary>
        /// Name or identifier of the page.
        /// </summary>
        /// <value>Name or identifier of the page.</value>
        [DataMember(Name="pageName", EmitDefaultValue=false)]
        public string PageName { get; set; }

        /// <summary>
        /// Number of visits to this page during the report period.
        /// </summary>
        /// <value>Number of visits to this page during the report period.</value>
        [DataMember(Name="visitCount", EmitDefaultValue=false)]
        public int? VisitCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserActivityReportTopVisitedPages {\n");
            sb.Append("  PageName: ").Append(PageName).Append("\n");
            sb.Append("  VisitCount: ").Append(VisitCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UserActivityReportTopVisitedPages);
        }

        /// <summary>
        /// Returns true if UserActivityReportTopVisitedPages instances are equal
        /// </summary>
        /// <param name="input">Instance of UserActivityReportTopVisitedPages to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserActivityReportTopVisitedPages input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PageName == input.PageName ||
                    (this.PageName != null &&
                    this.PageName.Equals(input.PageName))
                ) && 
                (
                    this.VisitCount == input.VisitCount ||
                    (this.VisitCount != null &&
                    this.VisitCount.Equals(input.VisitCount))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PageName != null)
                    hashCode = hashCode * 59 + this.PageName.GetHashCode();
                if (this.VisitCount != null)
                    hashCode = hashCode * 59 + this.VisitCount.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
