/* 
 * E-commerce API
 *
 * API for E-commerce Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandon.dunbar97@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// UsersResetpasswordBody
    /// </summary>
    [DataContract]
        public partial class UsersResetpasswordBody :  IEquatable<UsersResetpasswordBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UsersResetpasswordBody" /> class.
        /// </summary>
        /// <param name="resetToken">The reset token or code received in the email (required).</param>
        /// <param name="newPassword">The new password the user wants to set (required).</param>
        /// <param name="confirmPassword">Confirmation of the new password (required).</param>
        public UsersResetpasswordBody(string resetToken = default(string), string newPassword = default(string), string confirmPassword = default(string))
        {
            // to ensure "resetToken" is required (not null)
            if (resetToken == null)
            {
                throw new InvalidDataException("resetToken is a required property for UsersResetpasswordBody and cannot be null");
            }
            else
            {
                this.ResetToken = resetToken;
            }
            // to ensure "newPassword" is required (not null)
            if (newPassword == null)
            {
                throw new InvalidDataException("newPassword is a required property for UsersResetpasswordBody and cannot be null");
            }
            else
            {
                this.NewPassword = newPassword;
            }
            // to ensure "confirmPassword" is required (not null)
            if (confirmPassword == null)
            {
                throw new InvalidDataException("confirmPassword is a required property for UsersResetpasswordBody and cannot be null");
            }
            else
            {
                this.ConfirmPassword = confirmPassword;
            }
        }
        
        /// <summary>
        /// The reset token or code received in the email
        /// </summary>
        /// <value>The reset token or code received in the email</value>
        [DataMember(Name="resetToken", EmitDefaultValue=false)]
        public string ResetToken { get; set; }

        /// <summary>
        /// The new password the user wants to set
        /// </summary>
        /// <value>The new password the user wants to set</value>
        [DataMember(Name="newPassword", EmitDefaultValue=false)]
        public string NewPassword { get; set; }

        /// <summary>
        /// Confirmation of the new password
        /// </summary>
        /// <value>Confirmation of the new password</value>
        [DataMember(Name="confirmPassword", EmitDefaultValue=false)]
        public string ConfirmPassword { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UsersResetpasswordBody {\n");
            sb.Append("  ResetToken: ").Append(ResetToken).Append("\n");
            sb.Append("  NewPassword: ").Append(NewPassword).Append("\n");
            sb.Append("  ConfirmPassword: ").Append(ConfirmPassword).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UsersResetpasswordBody);
        }

        /// <summary>
        /// Returns true if UsersResetpasswordBody instances are equal
        /// </summary>
        /// <param name="input">Instance of UsersResetpasswordBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UsersResetpasswordBody input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ResetToken == input.ResetToken ||
                    (this.ResetToken != null &&
                    this.ResetToken.Equals(input.ResetToken))
                ) && 
                (
                    this.NewPassword == input.NewPassword ||
                    (this.NewPassword != null &&
                    this.NewPassword.Equals(input.NewPassword))
                ) && 
                (
                    this.ConfirmPassword == input.ConfirmPassword ||
                    (this.ConfirmPassword != null &&
                    this.ConfirmPassword.Equals(input.ConfirmPassword))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ResetToken != null)
                    hashCode = hashCode * 59 + this.ResetToken.GetHashCode();
                if (this.NewPassword != null)
                    hashCode = hashCode * 59 + this.NewPassword.GetHashCode();
                if (this.ConfirmPassword != null)
                    hashCode = hashCode * 59 + this.ConfirmPassword.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
