/* 
 * E-commerce API
 *
 * API for E-commerce Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandon.dunbar97@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UsersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class UsersApiTests
    {
        private UsersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UsersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UsersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' UsersApi
            //Assert.IsInstanceOfType(typeof(UsersApi), instance, "instance is a UsersApi");
        }

        /// <summary>
        /// Test ApiUsersForgotPasswordPost
        /// </summary>
        [Test]
        public void ApiUsersForgotPasswordPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UsersForgotpasswordBody body = null;
            //instance.ApiUsersForgotPasswordPost(body);
            
        }
        /// <summary>
        /// Test ApiUsersLoginPost
        /// </summary>
        [Test]
        public void ApiUsersLoginPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UserLogin body = null;
            //var response = instance.ApiUsersLoginPost(body);
            //Assert.IsInstanceOf<InlineResponse200> (response, "response is InlineResponse200");
        }
        /// <summary>
        /// Test ApiUsersNotificationsGet
        /// </summary>
        [Test]
        public void ApiUsersNotificationsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string status = null;
            //var response = instance.ApiUsersNotificationsGet(status);
            //Assert.IsInstanceOf<List<Notification>> (response, "response is List<Notification>");
        }
        /// <summary>
        /// Test ApiUsersNotificationsPut
        /// </summary>
        [Test]
        public void ApiUsersNotificationsPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UsersNotificationsBody body = null;
            //instance.ApiUsersNotificationsPut(body);
            
        }
        /// <summary>
        /// Test ApiUsersOrdersGet
        /// </summary>
        [Test]
        public void ApiUsersOrdersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? limit = null;
            //string status = null;
            //var response = instance.ApiUsersOrdersGet(page, limit, status);
            //Assert.IsInstanceOf<List<Order>> (response, "response is List<Order>");
        }
        /// <summary>
        /// Test ApiUsersProfileDelete
        /// </summary>
        [Test]
        public void ApiUsersProfileDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiUsersProfileDelete();
            
        }
        /// <summary>
        /// Test ApiUsersProfileGet
        /// </summary>
        [Test]
        public void ApiUsersProfileGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiUsersProfileGet();
            //Assert.IsInstanceOf<UserProfile> (response, "response is UserProfile");
        }
        /// <summary>
        /// Test ApiUsersProfilePasswordPut
        /// </summary>
        [Test]
        public void ApiUsersProfilePasswordPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProfilePasswordBody body = null;
            //instance.ApiUsersProfilePasswordPut(body);
            
        }
        /// <summary>
        /// Test ApiUsersProfilePut
        /// </summary>
        [Test]
        public void ApiUsersProfilePutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UserProfile body = null;
            //var response = instance.ApiUsersProfilePut(body);
            //Assert.IsInstanceOf<UserProfile> (response, "response is UserProfile");
        }
        /// <summary>
        /// Test ApiUsersRegisterPost
        /// </summary>
        [Test]
        public void ApiUsersRegisterPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UserRegistration body = null;
            //var response = instance.ApiUsersRegisterPost(body);
            //Assert.IsInstanceOf<UserProfile> (response, "response is UserProfile");
        }
        /// <summary>
        /// Test ApiUsersResetPasswordPost
        /// </summary>
        [Test]
        public void ApiUsersResetPasswordPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UsersResetpasswordBody body = null;
            //instance.ApiUsersResetPasswordPost(body);
            
        }
        /// <summary>
        /// Test ApiUsersReviewsGet
        /// </summary>
        [Test]
        public void ApiUsersReviewsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiUsersReviewsGet();
            //Assert.IsInstanceOf<List<Review>> (response, "response is List<Review>");
        }
        /// <summary>
        /// Test ApiUsersReviewsPost
        /// </summary>
        [Test]
        public void ApiUsersReviewsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ReviewInput body = null;
            //instance.ApiUsersReviewsPost(body);
            
        }
        /// <summary>
        /// Test ApiUsersWishlistsGet
        /// </summary>
        [Test]
        public void ApiUsersWishlistsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiUsersWishlistsGet();
            //Assert.IsInstanceOf<List<Wishlist>> (response, "response is List<Wishlist>");
        }
        /// <summary>
        /// Test ApiUsersWishlistsPost
        /// </summary>
        [Test]
        public void ApiUsersWishlistsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Wishlist body = null;
            //instance.ApiUsersWishlistsPost(body);
            
        }
    }

}
