# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Address(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, street: str=None, city: str=None, state: str=None, postal_code: str=None, country: str=None):  # noqa: E501
        """Address - a model defined in Swagger

        :param street: The street of this Address.  # noqa: E501
        :type street: str
        :param city: The city of this Address.  # noqa: E501
        :type city: str
        :param state: The state of this Address.  # noqa: E501
        :type state: str
        :param postal_code: The postal_code of this Address.  # noqa: E501
        :type postal_code: str
        :param country: The country of this Address.  # noqa: E501
        :type country: str
        """
        self.swagger_types = {
            'street': str,
            'city': str,
            'state': str,
            'postal_code': str,
            'country': str
        }

        self.attribute_map = {
            'street': 'street',
            'city': 'city',
            'state': 'state',
            'postal_code': 'postalCode',
            'country': 'country'
        }
        self._street = street
        self._city = city
        self._state = state
        self._postal_code = postal_code
        self._country = country

    @classmethod
    def from_dict(cls, dikt) -> 'Address':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Address of this Address.  # noqa: E501
        :rtype: Address
        """
        return util.deserialize_model(dikt, cls)

    @property
    def street(self) -> str:
        """Gets the street of this Address.

        Street address.  # noqa: E501

        :return: The street of this Address.
        :rtype: str
        """
        return self._street

    @street.setter
    def street(self, street: str):
        """Sets the street of this Address.

        Street address.  # noqa: E501

        :param street: The street of this Address.
        :type street: str
        """

        self._street = street

    @property
    def city(self) -> str:
        """Gets the city of this Address.

        City name.  # noqa: E501

        :return: The city of this Address.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city: str):
        """Sets the city of this Address.

        City name.  # noqa: E501

        :param city: The city of this Address.
        :type city: str
        """

        self._city = city

    @property
    def state(self) -> str:
        """Gets the state of this Address.

        State or region.  # noqa: E501

        :return: The state of this Address.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this Address.

        State or region.  # noqa: E501

        :param state: The state of this Address.
        :type state: str
        """

        self._state = state

    @property
    def postal_code(self) -> str:
        """Gets the postal_code of this Address.

        Postal or ZIP code.  # noqa: E501

        :return: The postal_code of this Address.
        :rtype: str
        """
        return self._postal_code

    @postal_code.setter
    def postal_code(self, postal_code: str):
        """Sets the postal_code of this Address.

        Postal or ZIP code.  # noqa: E501

        :param postal_code: The postal_code of this Address.
        :type postal_code: str
        """

        self._postal_code = postal_code

    @property
    def country(self) -> str:
        """Gets the country of this Address.

        Country name.  # noqa: E501

        :return: The country of this Address.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country: str):
        """Sets the country of this Address.

        Country name.  # noqa: E501

        :param country: The country of this Address.
        :type country: str
        """

        self._country = country
