# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Category(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, description: str=None, parent_category_id: int=None):  # noqa: E501
        """Category - a model defined in Swagger

        :param id: The id of this Category.  # noqa: E501
        :type id: int
        :param name: The name of this Category.  # noqa: E501
        :type name: str
        :param description: The description of this Category.  # noqa: E501
        :type description: str
        :param parent_category_id: The parent_category_id of this Category.  # noqa: E501
        :type parent_category_id: int
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'description': str,
            'parent_category_id': int
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description',
            'parent_category_id': 'parentCategoryId'
        }
        self._id = id
        self._name = name
        self._description = description
        self._parent_category_id = parent_category_id

    @classmethod
    def from_dict(cls, dikt) -> 'Category':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Category of this Category.  # noqa: E501
        :rtype: Category
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Category.

        Unique identifier for the category.  # noqa: E501

        :return: The id of this Category.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Category.

        Unique identifier for the category.  # noqa: E501

        :param id: The id of this Category.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Category.

        Name of the category.  # noqa: E501

        :return: The name of this Category.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Category.

        Name of the category.  # noqa: E501

        :param name: The name of this Category.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this Category.

        A brief description of the category.  # noqa: E501

        :return: The description of this Category.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Category.

        A brief description of the category.  # noqa: E501

        :param description: The description of this Category.
        :type description: str
        """

        self._description = description

    @property
    def parent_category_id(self) -> int:
        """Gets the parent_category_id of this Category.

        Identifier for the parent category (if it's a sub-category).  # noqa: E501

        :return: The parent_category_id of this Category.
        :rtype: int
        """
        return self._parent_category_id

    @parent_category_id.setter
    def parent_category_id(self, parent_category_id: int):
        """Sets the parent_category_id of this Category.

        Identifier for the parent category (if it's a sub-category).  # noqa: E501

        :param parent_category_id: The parent_category_id of this Category.
        :type parent_category_id: int
        """

        self._parent_category_id = parent_category_id
