# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PromotionUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, promotion_id: int=None, name: str=None, type: str=None, value: float=None, start_date: datetime=None, end_date: datetime=None, applicable_products: List[int]=None, notes: str=None):  # noqa: E501
        """PromotionUpdate - a model defined in Swagger

        :param promotion_id: The promotion_id of this PromotionUpdate.  # noqa: E501
        :type promotion_id: int
        :param name: The name of this PromotionUpdate.  # noqa: E501
        :type name: str
        :param type: The type of this PromotionUpdate.  # noqa: E501
        :type type: str
        :param value: The value of this PromotionUpdate.  # noqa: E501
        :type value: float
        :param start_date: The start_date of this PromotionUpdate.  # noqa: E501
        :type start_date: datetime
        :param end_date: The end_date of this PromotionUpdate.  # noqa: E501
        :type end_date: datetime
        :param applicable_products: The applicable_products of this PromotionUpdate.  # noqa: E501
        :type applicable_products: List[int]
        :param notes: The notes of this PromotionUpdate.  # noqa: E501
        :type notes: str
        """
        self.swagger_types = {
            'promotion_id': int,
            'name': str,
            'type': str,
            'value': float,
            'start_date': datetime,
            'end_date': datetime,
            'applicable_products': List[int],
            'notes': str
        }

        self.attribute_map = {
            'promotion_id': 'promotionId',
            'name': 'name',
            'type': 'type',
            'value': 'value',
            'start_date': 'startDate',
            'end_date': 'endDate',
            'applicable_products': 'applicableProducts',
            'notes': 'notes'
        }
        self._promotion_id = promotion_id
        self._name = name
        self._type = type
        self._value = value
        self._start_date = start_date
        self._end_date = end_date
        self._applicable_products = applicable_products
        self._notes = notes

    @classmethod
    def from_dict(cls, dikt) -> 'PromotionUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PromotionUpdate of this PromotionUpdate.  # noqa: E501
        :rtype: PromotionUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def promotion_id(self) -> int:
        """Gets the promotion_id of this PromotionUpdate.

        Unique identifier for the promotion. This is typically used for reference and not for update purposes.  # noqa: E501

        :return: The promotion_id of this PromotionUpdate.
        :rtype: int
        """
        return self._promotion_id

    @promotion_id.setter
    def promotion_id(self, promotion_id: int):
        """Sets the promotion_id of this PromotionUpdate.

        Unique identifier for the promotion. This is typically used for reference and not for update purposes.  # noqa: E501

        :param promotion_id: The promotion_id of this PromotionUpdate.
        :type promotion_id: int
        """

        self._promotion_id = promotion_id

    @property
    def name(self) -> str:
        """Gets the name of this PromotionUpdate.

        Updated name or title of the promotion.  # noqa: E501

        :return: The name of this PromotionUpdate.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this PromotionUpdate.

        Updated name or title of the promotion.  # noqa: E501

        :param name: The name of this PromotionUpdate.
        :type name: str
        """

        self._name = name

    @property
    def type(self) -> str:
        """Gets the type of this PromotionUpdate.

        Type of promotion, e.g., percentage discount, flat discount, etc.  # noqa: E501

        :return: The type of this PromotionUpdate.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this PromotionUpdate.

        Type of promotion, e.g., percentage discount, flat discount, etc.  # noqa: E501

        :param type: The type of this PromotionUpdate.
        :type type: str
        """
        allowed_values = ["percentage", "flat_discount", "buy_one_get_one", "other"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def value(self) -> float:
        """Gets the value of this PromotionUpdate.

        The value associated with the promotion. For example, if it's a percentage discount, this might be \"10\" for 10%.  # noqa: E501

        :return: The value of this PromotionUpdate.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value: float):
        """Sets the value of this PromotionUpdate.

        The value associated with the promotion. For example, if it's a percentage discount, this might be \"10\" for 10%.  # noqa: E501

        :param value: The value of this PromotionUpdate.
        :type value: float
        """

        self._value = value

    @property
    def start_date(self) -> datetime:
        """Gets the start_date of this PromotionUpdate.

        Updated start date and time for when the promotion becomes active.  # noqa: E501

        :return: The start_date of this PromotionUpdate.
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date: datetime):
        """Sets the start_date of this PromotionUpdate.

        Updated start date and time for when the promotion becomes active.  # noqa: E501

        :param start_date: The start_date of this PromotionUpdate.
        :type start_date: datetime
        """

        self._start_date = start_date

    @property
    def end_date(self) -> datetime:
        """Gets the end_date of this PromotionUpdate.

        Updated end date and time for when the promotion expires.  # noqa: E501

        :return: The end_date of this PromotionUpdate.
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date: datetime):
        """Sets the end_date of this PromotionUpdate.

        Updated end date and time for when the promotion expires.  # noqa: E501

        :param end_date: The end_date of this PromotionUpdate.
        :type end_date: datetime
        """

        self._end_date = end_date

    @property
    def applicable_products(self) -> List[int]:
        """Gets the applicable_products of this PromotionUpdate.

        List of product IDs to which the promotion is applicable. If empty, it might be applicable to all products or specific categories.  # noqa: E501

        :return: The applicable_products of this PromotionUpdate.
        :rtype: List[int]
        """
        return self._applicable_products

    @applicable_products.setter
    def applicable_products(self, applicable_products: List[int]):
        """Sets the applicable_products of this PromotionUpdate.

        List of product IDs to which the promotion is applicable. If empty, it might be applicable to all products or specific categories.  # noqa: E501

        :param applicable_products: The applicable_products of this PromotionUpdate.
        :type applicable_products: List[int]
        """

        self._applicable_products = applicable_products

    @property
    def notes(self) -> str:
        """Gets the notes of this PromotionUpdate.

        Any additional notes or updates about the promotion.  # noqa: E501

        :return: The notes of this PromotionUpdate.
        :rtype: str
        """
        return self._notes

    @notes.setter
    def notes(self, notes: str):
        """Sets the notes of this PromotionUpdate.

        Any additional notes or updates about the promotion.  # noqa: E501

        :param notes: The notes of this PromotionUpdate.
        :type notes: str
        """

        self._notes = notes
