# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SalesReportDailyBreakdown(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: date=None, sales: int=None, revenue: float=None):  # noqa: E501
        """SalesReportDailyBreakdown - a model defined in Swagger

        :param _date: The _date of this SalesReportDailyBreakdown.  # noqa: E501
        :type _date: date
        :param sales: The sales of this SalesReportDailyBreakdown.  # noqa: E501
        :type sales: int
        :param revenue: The revenue of this SalesReportDailyBreakdown.  # noqa: E501
        :type revenue: float
        """
        self.swagger_types = {
            '_date': date,
            'sales': int,
            'revenue': float
        }

        self.attribute_map = {
            '_date': 'date',
            'sales': 'sales',
            'revenue': 'revenue'
        }
        self.__date = _date
        self._sales = sales
        self._revenue = revenue

    @classmethod
    def from_dict(cls, dikt) -> 'SalesReportDailyBreakdown':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SalesReport_dailyBreakdown of this SalesReportDailyBreakdown.  # noqa: E501
        :rtype: SalesReportDailyBreakdown
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> date:
        """Gets the _date of this SalesReportDailyBreakdown.

        Specific date in the report period.  # noqa: E501

        :return: The _date of this SalesReportDailyBreakdown.
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date: date):
        """Sets the _date of this SalesReportDailyBreakdown.

        Specific date in the report period.  # noqa: E501

        :param _date: The _date of this SalesReportDailyBreakdown.
        :type _date: date
        """

        self.__date = _date

    @property
    def sales(self) -> int:
        """Gets the sales of this SalesReportDailyBreakdown.

        Number of sales on that date.  # noqa: E501

        :return: The sales of this SalesReportDailyBreakdown.
        :rtype: int
        """
        return self._sales

    @sales.setter
    def sales(self, sales: int):
        """Sets the sales of this SalesReportDailyBreakdown.

        Number of sales on that date.  # noqa: E501

        :param sales: The sales of this SalesReportDailyBreakdown.
        :type sales: int
        """

        self._sales = sales

    @property
    def revenue(self) -> float:
        """Gets the revenue of this SalesReportDailyBreakdown.

        Revenue generated on that date.  # noqa: E501

        :return: The revenue of this SalesReportDailyBreakdown.
        :rtype: float
        """
        return self._revenue

    @revenue.setter
    def revenue(self, revenue: float):
        """Sets the revenue of this SalesReportDailyBreakdown.

        Revenue generated on that date.  # noqa: E501

        :param revenue: The revenue of this SalesReportDailyBreakdown.
        :type revenue: float
        """

        self._revenue = revenue
