# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserProfile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, username: str=None, email: str=None):  # noqa: E501
        """UserProfile - a model defined in Swagger

        :param username: The username of this UserProfile.  # noqa: E501
        :type username: str
        :param email: The email of this UserProfile.  # noqa: E501
        :type email: str
        """
        self.swagger_types = {
            'username': str,
            'email': str
        }

        self.attribute_map = {
            'username': 'username',
            'email': 'email'
        }
        self._username = username
        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'UserProfile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserProfile of this UserProfile.  # noqa: E501
        :rtype: UserProfile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this UserProfile.


        :return: The username of this UserProfile.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this UserProfile.


        :param username: The username of this UserProfile.
        :type username: str
        """

        self._username = username

    @property
    def email(self) -> str:
        """Gets the email of this UserProfile.


        :return: The email of this UserProfile.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this UserProfile.


        :param email: The email of this UserProfile.
        :type email: str
        """

        self._email = email
