# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.product_reference import ProductReference  # noqa: F401,E501
from swagger_server import util


class Wishlist(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, description: str=None, items: List[ProductReference]=None):  # noqa: E501
        """Wishlist - a model defined in Swagger

        :param id: The id of this Wishlist.  # noqa: E501
        :type id: int
        :param name: The name of this Wishlist.  # noqa: E501
        :type name: str
        :param description: The description of this Wishlist.  # noqa: E501
        :type description: str
        :param items: The items of this Wishlist.  # noqa: E501
        :type items: List[ProductReference]
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'description': str,
            'items': List[ProductReference]
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description',
            'items': 'items'
        }
        self._id = id
        self._name = name
        self._description = description
        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'Wishlist':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Wishlist of this Wishlist.  # noqa: E501
        :rtype: Wishlist
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Wishlist.

        Unique identifier for the wishlist.  # noqa: E501

        :return: The id of this Wishlist.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Wishlist.

        Unique identifier for the wishlist.  # noqa: E501

        :param id: The id of this Wishlist.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Wishlist.

        Name or title of the wishlist.  # noqa: E501

        :return: The name of this Wishlist.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Wishlist.

        Name or title of the wishlist.  # noqa: E501

        :param name: The name of this Wishlist.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this Wishlist.

        A brief description or note for the wishlist.  # noqa: E501

        :return: The description of this Wishlist.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Wishlist.

        A brief description or note for the wishlist.  # noqa: E501

        :param description: The description of this Wishlist.
        :type description: str
        """

        self._description = description

    @property
    def items(self) -> List[ProductReference]:
        """Gets the items of this Wishlist.

        List of products/items in the wishlist.  # noqa: E501

        :return: The items of this Wishlist.
        :rtype: List[ProductReference]
        """
        return self._items

    @items.setter
    def items(self, items: List[ProductReference]):
        """Sets the items of this Wishlist.

        List of products/items in the wishlist.  # noqa: E501

        :param items: The items of this Wishlist.
        :type items: List[ProductReference]
        """

        self._items = items
