/* 
 * E-commerce API
 *
 * API for E-commerce Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandon.dunbar97@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InventoryUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InventoryUpdateTests
    {
        // TODO uncomment below to declare an instance variable for InventoryUpdate
        //private InventoryUpdate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InventoryUpdate
            //instance = new InventoryUpdate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InventoryUpdate
        /// </summary>
        [Test]
        public void InventoryUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InventoryUpdate
            //Assert.IsInstanceOfType<InventoryUpdate> (instance, "variable 'instance' is a InventoryUpdate");
        }


        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Test]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }
        /// <summary>
        /// Test the property 'CurrentStock'
        /// </summary>
        [Test]
        public void CurrentStockTest()
        {
            // TODO unit test for the property 'CurrentStock'
        }
        /// <summary>
        /// Test the property 'RestockDate'
        /// </summary>
        [Test]
        public void RestockDateTest()
        {
            // TODO unit test for the property 'RestockDate'
        }
        /// <summary>
        /// Test the property 'Threshold'
        /// </summary>
        [Test]
        public void ThresholdTest()
        {
            // TODO unit test for the property 'Threshold'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Test]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

    }

}
