/* 
 * E-commerce API
 *
 * API for E-commerce Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandon.dunbar97@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InventoryItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InventoryItemTests
    {
        // TODO uncomment below to declare an instance variable for InventoryItem
        //private InventoryItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InventoryItem
            //instance = new InventoryItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InventoryItem
        /// </summary>
        [Test]
        public void InventoryItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InventoryItem
            //Assert.IsInstanceOfType<InventoryItem> (instance, "variable 'instance' is a InventoryItem");
        }


        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Test]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }
        /// <summary>
        /// Test the property 'ProductName'
        /// </summary>
        [Test]
        public void ProductNameTest()
        {
            // TODO unit test for the property 'ProductName'
        }
        /// <summary>
        /// Test the property 'CurrentStock'
        /// </summary>
        [Test]
        public void CurrentStockTest()
        {
            // TODO unit test for the property 'CurrentStock'
        }
        /// <summary>
        /// Test the property 'RestockThreshold'
        /// </summary>
        [Test]
        public void RestockThresholdTest()
        {
            // TODO unit test for the property 'RestockThreshold'
        }
        /// <summary>
        /// Test the property 'LastRestockDate'
        /// </summary>
        [Test]
        public void LastRestockDateTest()
        {
            // TODO unit test for the property 'LastRestockDate'
        }
        /// <summary>
        /// Test the property 'NextRestockDate'
        /// </summary>
        [Test]
        public void NextRestockDateTest()
        {
            // TODO unit test for the property 'NextRestockDate'
        }
        /// <summary>
        /// Test the property 'Supplier'
        /// </summary>
        [Test]
        public void SupplierTest()
        {
            // TODO unit test for the property 'Supplier'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Test]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

    }

}
