/* 
 * E-commerce API
 *
 * API for E-commerce Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandon.dunbar97@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MonitoringMetric
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MonitoringMetricTests
    {
        // TODO uncomment below to declare an instance variable for MonitoringMetric
        //private MonitoringMetric instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MonitoringMetric
            //instance = new MonitoringMetric();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MonitoringMetric
        /// </summary>
        [Test]
        public void MonitoringMetricInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MonitoringMetric
            //Assert.IsInstanceOfType<MonitoringMetric> (instance, "variable 'instance' is a MonitoringMetric");
        }


        /// <summary>
        /// Test the property 'MetricId'
        /// </summary>
        [Test]
        public void MetricIdTest()
        {
            // TODO unit test for the property 'MetricId'
        }
        /// <summary>
        /// Test the property 'MetricName'
        /// </summary>
        [Test]
        public void MetricNameTest()
        {
            // TODO unit test for the property 'MetricName'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Test]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
