/* 
 * E-commerce API
 *
 * API for E-commerce Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandon.dunbar97@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PartnershipCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PartnershipCreateTests
    {
        // TODO uncomment below to declare an instance variable for PartnershipCreate
        //private PartnershipCreate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PartnershipCreate
            //instance = new PartnershipCreate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PartnershipCreate
        /// </summary>
        [Test]
        public void PartnershipCreateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PartnershipCreate
            //Assert.IsInstanceOfType<PartnershipCreate> (instance, "variable 'instance' is a PartnershipCreate");
        }


        /// <summary>
        /// Test the property 'PartnerName'
        /// </summary>
        [Test]
        public void PartnerNameTest()
        {
            // TODO unit test for the property 'PartnerName'
        }
        /// <summary>
        /// Test the property 'ContactPerson'
        /// </summary>
        [Test]
        public void ContactPersonTest()
        {
            // TODO unit test for the property 'ContactPerson'
        }
        /// <summary>
        /// Test the property 'ContactEmail'
        /// </summary>
        [Test]
        public void ContactEmailTest()
        {
            // TODO unit test for the property 'ContactEmail'
        }
        /// <summary>
        /// Test the property 'PartnershipType'
        /// </summary>
        [Test]
        public void PartnershipTypeTest()
        {
            // TODO unit test for the property 'PartnershipType'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'Terms'
        /// </summary>
        [Test]
        public void TermsTest()
        {
            // TODO unit test for the property 'Terms'
        }
        /// <summary>
        /// Test the property 'Benefits'
        /// </summary>
        [Test]
        public void BenefitsTest()
        {
            // TODO unit test for the property 'Benefits'
        }
        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Test]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }

    }

}
