/* 
 * E-commerce API
 *
 * API for E-commerce Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandon.dunbar97@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PlatformSettingsShippingConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PlatformSettingsShippingConfigTests
    {
        // TODO uncomment below to declare an instance variable for PlatformSettingsShippingConfig
        //private PlatformSettingsShippingConfig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PlatformSettingsShippingConfig
            //instance = new PlatformSettingsShippingConfig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PlatformSettingsShippingConfig
        /// </summary>
        [Test]
        public void PlatformSettingsShippingConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PlatformSettingsShippingConfig
            //Assert.IsInstanceOfType<PlatformSettingsShippingConfig> (instance, "variable 'instance' is a PlatformSettingsShippingConfig");
        }


        /// <summary>
        /// Test the property 'DefaultProvider'
        /// </summary>
        [Test]
        public void DefaultProviderTest()
        {
            // TODO unit test for the property 'DefaultProvider'
        }
        /// <summary>
        /// Test the property 'Rates'
        /// </summary>
        [Test]
        public void RatesTest()
        {
            // TODO unit test for the property 'Rates'
        }

    }

}
