/* 
 * E-commerce API
 *
 * API for E-commerce Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandon.dunbar97@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProductImage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProductImageTests
    {
        // TODO uncomment below to declare an instance variable for ProductImage
        //private ProductImage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProductImage
            //instance = new ProductImage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProductImage
        /// </summary>
        [Test]
        public void ProductImageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProductImage
            //Assert.IsInstanceOfType<ProductImage> (instance, "variable 'instance' is a ProductImage");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'AltText'
        /// </summary>
        [Test]
        public void AltTextTest()
        {
            // TODO unit test for the property 'AltText'
        }
        /// <summary>
        /// Test the property 'UploadedAt'
        /// </summary>
        [Test]
        public void UploadedAtTest()
        {
            // TODO unit test for the property 'UploadedAt'
        }

    }

}
