/* 
 * E-commerce API
 *
 * API for E-commerce Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandon.dunbar97@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProductPriceHistoryItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProductPriceHistoryItemTests
    {
        // TODO uncomment below to declare an instance variable for ProductPriceHistoryItem
        //private ProductPriceHistoryItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProductPriceHistoryItem
            //instance = new ProductPriceHistoryItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProductPriceHistoryItem
        /// </summary>
        [Test]
        public void ProductPriceHistoryItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProductPriceHistoryItem
            //Assert.IsInstanceOfType<ProductPriceHistoryItem> (instance, "variable 'instance' is a ProductPriceHistoryItem");
        }


        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'EffectiveDate'
        /// </summary>
        [Test]
        public void EffectiveDateTest()
        {
            // TODO unit test for the property 'EffectiveDate'
        }
        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Test]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }

    }

}
