/* 
 * E-commerce API
 *
 * API for E-commerce Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandon.dunbar97@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReviewUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReviewUpdateTests
    {
        // TODO uncomment below to declare an instance variable for ReviewUpdate
        //private ReviewUpdate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReviewUpdate
            //instance = new ReviewUpdate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReviewUpdate
        /// </summary>
        [Test]
        public void ReviewUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReviewUpdate
            //Assert.IsInstanceOfType<ReviewUpdate> (instance, "variable 'instance' is a ReviewUpdate");
        }


        /// <summary>
        /// Test the property 'ReviewId'
        /// </summary>
        [Test]
        public void ReviewIdTest()
        {
            // TODO unit test for the property 'ReviewId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'AdminComment'
        /// </summary>
        [Test]
        public void AdminCommentTest()
        {
            // TODO unit test for the property 'AdminComment'
        }
        /// <summary>
        /// Test the property 'UpdatedContent'
        /// </summary>
        [Test]
        public void UpdatedContentTest()
        {
            // TODO unit test for the property 'UpdatedContent'
        }

    }

}
