/* 
 * E-commerce API
 *
 * API for E-commerce Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandon.dunbar97@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SalesReportDailyBreakdown
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SalesReportDailyBreakdownTests
    {
        // TODO uncomment below to declare an instance variable for SalesReportDailyBreakdown
        //private SalesReportDailyBreakdown instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SalesReportDailyBreakdown
            //instance = new SalesReportDailyBreakdown();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SalesReportDailyBreakdown
        /// </summary>
        [Test]
        public void SalesReportDailyBreakdownInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SalesReportDailyBreakdown
            //Assert.IsInstanceOfType<SalesReportDailyBreakdown> (instance, "variable 'instance' is a SalesReportDailyBreakdown");
        }


        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Sales'
        /// </summary>
        [Test]
        public void SalesTest()
        {
            // TODO unit test for the property 'Sales'
        }
        /// <summary>
        /// Test the property 'Revenue'
        /// </summary>
        [Test]
        public void RevenueTest()
        {
            // TODO unit test for the property 'Revenue'
        }

    }

}
