/* 
 * E-commerce API
 *
 * API for E-commerce Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandon.dunbar97@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserActivityReport
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserActivityReportTests
    {
        // TODO uncomment below to declare an instance variable for UserActivityReport
        //private UserActivityReport instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserActivityReport
            //instance = new UserActivityReport();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserActivityReport
        /// </summary>
        [Test]
        public void UserActivityReportInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserActivityReport
            //Assert.IsInstanceOfType<UserActivityReport> (instance, "variable 'instance' is a UserActivityReport");
        }


        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'TotalUsers'
        /// </summary>
        [Test]
        public void TotalUsersTest()
        {
            // TODO unit test for the property 'TotalUsers'
        }
        /// <summary>
        /// Test the property 'ActiveUsers'
        /// </summary>
        [Test]
        public void ActiveUsersTest()
        {
            // TODO unit test for the property 'ActiveUsers'
        }
        /// <summary>
        /// Test the property 'AverageSessionDuration'
        /// </summary>
        [Test]
        public void AverageSessionDurationTest()
        {
            // TODO unit test for the property 'AverageSessionDuration'
        }
        /// <summary>
        /// Test the property 'TopVisitedPages'
        /// </summary>
        [Test]
        public void TopVisitedPagesTest()
        {
            // TODO unit test for the property 'TopVisitedPages'
        }
        /// <summary>
        /// Test the property 'DailyLogins'
        /// </summary>
        [Test]
        public void DailyLoginsTest()
        {
            // TODO unit test for the property 'DailyLogins'
        }

    }

}
