/* 
 * E-commerce API
 *
 * API for E-commerce Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandon.dunbar97@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UsersResetpasswordBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UsersResetpasswordBodyTests
    {
        // TODO uncomment below to declare an instance variable for UsersResetpasswordBody
        //private UsersResetpasswordBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UsersResetpasswordBody
            //instance = new UsersResetpasswordBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UsersResetpasswordBody
        /// </summary>
        [Test]
        public void UsersResetpasswordBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UsersResetpasswordBody
            //Assert.IsInstanceOfType<UsersResetpasswordBody> (instance, "variable 'instance' is a UsersResetpasswordBody");
        }


        /// <summary>
        /// Test the property 'ResetToken'
        /// </summary>
        [Test]
        public void ResetTokenTest()
        {
            // TODO unit test for the property 'ResetToken'
        }
        /// <summary>
        /// Test the property 'NewPassword'
        /// </summary>
        [Test]
        public void NewPasswordTest()
        {
            // TODO unit test for the property 'NewPassword'
        }
        /// <summary>
        /// Test the property 'ConfirmPassword'
        /// </summary>
        [Test]
        public void ConfirmPasswordTest()
        {
            // TODO unit test for the property 'ConfirmPassword'
        }

    }

}
