/* 
 * E-commerce API
 *
 * API for E-commerce Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandon.dunbar97@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserActivityReportTopVisitedPages
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserActivityReportTopVisitedPagesTests
    {
        // TODO uncomment below to declare an instance variable for UserActivityReportTopVisitedPages
        //private UserActivityReportTopVisitedPages instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserActivityReportTopVisitedPages
            //instance = new UserActivityReportTopVisitedPages();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserActivityReportTopVisitedPages
        /// </summary>
        [Test]
        public void UserActivityReportTopVisitedPagesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserActivityReportTopVisitedPages
            //Assert.IsInstanceOfType<UserActivityReportTopVisitedPages> (instance, "variable 'instance' is a UserActivityReportTopVisitedPages");
        }


        /// <summary>
        /// Test the property 'PageName'
        /// </summary>
        [Test]
        public void PageNameTest()
        {
            // TODO unit test for the property 'PageName'
        }
        /// <summary>
        /// Test the property 'VisitCount'
        /// </summary>
        [Test]
        public void VisitCountTest()
        {
            // TODO unit test for the property 'VisitCount'
        }

    }

}
